version: 2

models:
  - name: int_news_union
    description: >
      Intermediate model that unions asset-specific news with broader market
      and blog news into a single, standardized news dataset. This model
      harmonizes fields and data types across sources to provide a consistent
      view of news articles for downstream analytics and enrichment.

    config:

      freshness:
        warn_after:
          count: 24
          period: hour
      tags: [market, blog, asset, news]

    columns:
      - name: id_news_article
        data_type: string
        description: >
          Unique identifier for the news article across all source systems.
          Used to deduplicate and track articles in downstream models.
        tests:
          - not_null
          - unique

      - name: desc_news_title
        data_type: string
        description: >
          Headline or title of the news article as published by the source.
        tests:
          - not_null

      - name: desc_news_source
        data_type: string
        description: >
          Name of the originating publisher or platform (e.g., asset news
          provider, market news outlet, or blog).
        tests:
          - not_null

      - name: dt_news_posting
        data_type: timestamp
        description: >
          Timestamp indicating when the news article was published or posted
          by the source.
        tests:
          - not_null

      - name: desc_news_url
        data_type: string
        description: >
          Canonical URL linking to the full news article.
        tests:
          - not_null
          - unique

      - name: desc_news_category
        data_type: string
        description: >
          High-level category or topic assigned to the news article by the
          source or derived during ingestion (e.g., Stock, Market, Blog).
        tests:
          - not_null
          - accepted_values:
              values: ["Stock", "Market", "Blog"]

      - name: desc_news_related_tickers
        data_type: string
        description: >
          List of related asset tickers or symbols mentioned in the article,
          typically derived from source metadata or entity extraction.
        tests:
          - not_null

      - name: audit_loaded_at
        data_type: int
        description: "Batch or system date (YYYYMMDD formated as integer) indicating when the record was loaded into the data warehouse."
        tests:
          - not_null

      - name: audit_created_at
        data_type: timestamp
        description: "Timestamp indicating when the record was created."
        tests:
          - not_null