CREATE TABLE raw.finviz.screener_data (
  no BIGINT,
  ticker STRING,
  company STRING,
  sector STRING,
  industry STRING,
  country STRING,
  market_cap DOUBLE,
  p_e DOUBLE,
  forward_p_e DOUBLE,
  peg DOUBLE,
  p_s DOUBLE,
  p_b DOUBLE,
  p_cash DOUBLE,
  p_free_cash_flow DOUBLE,
  dividend_yield STRING,
  payout_ratio STRING,
  eps_ttm DOUBLE,
  eps_growth_this_year STRING,
  eps_growth_next_year STRING,
  eps_growth_past_5_years STRING,
  eps_growth_next_5_years STRING,
  sales_growth_past_5_years STRING,
  eps_growth_quarter_over_quarter STRING,
  sales_growth_quarter_over_quarter STRING,
  shares_outstanding DOUBLE,
  shares_float DOUBLE,
  insider_ownership STRING,
  insider_transactions STRING,
  institutional_ownership STRING,
  institutional_transactions STRING,
  short_float STRING,
  short_ratio DOUBLE,
  return_on_assets STRING,
  return_on_equity STRING,
  return_on_invested_capital STRING,
  current_ratio DOUBLE,
  quick_ratio DOUBLE,
  lt_debt_equity DOUBLE,
  total_debt_equity DOUBLE,
  gross_margin STRING,
  operating_margin STRING,
  profit_margin STRING,
  performance_week STRING,
  performance_month STRING,
  performance_quarter STRING,
  performance_half_year STRING,
  performance_year STRING,
  performance_ytd STRING,
  beta DOUBLE,
  average_true_range DOUBLE,
  volatility_week STRING,
  volatility_month STRING,
  `20_day_simple_moving_average` STRING,
  `50_day_simple_moving_average` STRING,
  `200_day_simple_moving_average` STRING,
  `50_day_high` STRING,
  `50_day_low` STRING,
  `52_week_high` STRING,
  `52_week_low` STRING,
  relative_strength_index_14 DOUBLE,
  change_from_open STRING,
  gap STRING,
  analyst_recom DOUBLE,
  average_volume DOUBLE,
  relative_volume DOUBLE,
  price DOUBLE,
  change STRING,
  earnings_date STRING,
  target_price DOUBLE,
  ipo_date STRING,
  after_hours_close DOUBLE,
  after_hours_change STRING,
  book_sh DOUBLE,
  cash_sh DOUBLE,
  dividend DOUBLE,
  employees DOUBLE,
  eps_next_q DOUBLE,
  income DOUBLE,
  index STRING,
  optionable STRING,
  prev_close DOUBLE,
  sales DOUBLE,
  shortable STRING,
  short_interest DOUBLE,
  float_pct STRING,
  open DOUBLE,
  high DOUBLE,
  low DOUBLE,
  trades BIGINT,
  performance_1_minute STRING,
  performance_2_minutes STRING,
  performance_3_minutes STRING,
  performance_5_minutes STRING,
  performance_10_minutes STRING,
  performance_15_minutes STRING,
  performance_30_minutes STRING,
  performance_1_hour STRING,
  performance_2_hours STRING,
  performance_4_hours STRING,
  asset_type DOUBLE,
  etf_type DOUBLE,
  region DOUBLE,
  single_category DOUBLE,
  sector_theme DOUBLE,
  tags DOUBLE,
  active_passive DOUBLE,
  net_expense_ratio DOUBLE,
  total_holdings DOUBLE,
  assets_under_management DOUBLE,
  net_asset_value DOUBLE,
  net_asset_value_pct DOUBLE,
  net_flows_1_month DOUBLE,
  net_flows_pct_1_month DOUBLE,
  net_flows_3_month DOUBLE,
  net_flows_pct_3_month DOUBLE,
  net_flows_ytd DOUBLE,
  net_flows_pct_ytd DOUBLE,
  net_flows_1_year DOUBLE,
  net_flows_pct_1_year DOUBLE,
  return_1_year DOUBLE,
  return_3_year DOUBLE,
  return_5_year DOUBLE,
  return_10_year DOUBLE,
  return_since_inception DOUBLE,
  all_time_high STRING,
  all_time_low STRING,
  eps_surprise STRING,
  revenue_surprise STRING,
  exchange STRING,
  dividend_ttm DOUBLE,
  dividend_ex_date STRING,
  eps_year_over_year_ttm STRING,
  sales_year_over_year_ttm STRING,
  `52_week_range` STRING,
  news_time STRING,
  news_url STRING,
  news_title STRING,
  performance_3_years STRING,
  performance_5_years STRING,
  performance_10_years STRING,
  after_hours_volume DOUBLE,
  eps_growth_past_3_years STRING,
  sales_growth_past_3_years STRING,
  enterprise_value DOUBLE,
  ev_ebitda DOUBLE,
  ev_sales DOUBLE,
  dividend_growth_1_year STRING,
  dividend_growth_3_years STRING,
  dividend_growth_5_years STRING,
  load_date STRING,
  volume DOUBLE)
USING delta
PARTITIONED BY (load_date)
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd');

CREATE TABLE raw.finviz.statements_data (
  load_date STRING,
  ticker STRING,
  period STRING,
  statement STRING,
  timeframe STRING,
  line_item STRING,
  value STRING)
USING delta
PARTITIONED BY (load_date)
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd');

CREATE TABLE raw.finviz.news_data (
  title STRING,
  source STRING,
  date STRING,
  url STRING,
  category STRING,
  load_date STRING)
USING delta
PARTITIONED BY (load_date)
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7');