version: 2

snapshots:
  - name: asset_identity_snapshot
    description: >
      Snapshot tracking changes to asset identity and classification attributes
      sourced from Finviz. Uses a check strategy on descriptive columns to
      capture historical changes while ignoring hard deletes to preserve historical
      data integrity.

    columns:
      - name: desc_ticker
        data_type: string
        description: "Stock ticker symbol identifying the publicly traded company."
        tests:
          - not_null

      - name: desc_company
        data_type: string
        description: "Full company name as listed on Finviz screener."
        tests:
          - not_null

      - name: desc_sector
        data_type: string
        description: "Economic sector classification assigned to the stock (e.g., Technology, Healthcare)."
        tests:
          - not_null

      - name: desc_industry
        data_type: string
        description: "Industry classification within the broader sector."
        tests:
          - not_null

      - name: desc_country
        data_type: string
        description: "Country where the company is headquartered or primarily operates."
        tests:
          - not_null

      - name: desc_exchange
        data_type: string
        description: "Stock exchange on which the company's shares are primarily listed."

      - name: desc_index
        data_type: string
        description: "Major market indexes in which the stock is included (e.g., S&P 500, NASDAQ 100)."

      - name: audit_loaded_at
        data_type: int
        description: "Batch or system date (YYYYMMDD formated as integer) indicating when the record was loaded into the data warehouse."
        tests:
          - not_null

      - name: audit_created_at
        data_type: timestamp
        description: "Timestamp indicating when the record was created."
        tests:
          - not_null

      - name: dbt_scd_id
        data_type: string
        description: "Unique identifier generated by dbt for each SCD record"
        tests:
          - not_null

      - name: dbt_updated_at
        data_type: timestamp
        description: "Timestamp of the source record used to detect changes"

      - name: dbt_valid_from
        data_type: timestamp
        description: "Timestamp when this version of the record became valid"
        tests:
          - not_null

      - name: dbt_valid_to
        data_type: timestamp
        description: "Timestamp when this version of the record stopped being valid"